server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/accomodations/**, 
        - id: assigningstatus
          uri: http://localhost:8083
          predicates:
            - Path=/assignHouseKeepers/**, 
        - id: room
          uri: http://localhost:8084
          predicates:
            - Path=/rooms/**, 
        - id: cleaningstatus
          uri: http://localhost:8085
          predicates:
            - Path=/cleaningStatuses/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/accomodations/**, 
        - id: assigningstatus
          uri: http://assigningstatus:8080
          predicates:
            - Path=/assignHouseKeepers/**, 
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/**, 
        - id: cleaningstatus
          uri: http://cleaningstatus:8080
          predicates:
            - Path=/cleaningStatuses/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
